In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
print("Array:",arr)
print()

zeros=np.zeros((2,3))
ones=np.ones((2,2))
arange_arr=np.arange(0,10,2)
print("Zeros:\n",zeros)
print()
print("Ones\n:",ones)
print()
print("Arange:",arange_arr)

Array: [1 2 3 4 5]

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones
: [[1. 1.]
 [1. 1.]]

Arange: [0 2 4 6 8]


In [3]:
print("arr[::2] (every 2nd element): ",arr[::2])

arr[::2] (every 2nd element):  [1 3 5]


In [4]:
mat=np.array([[10,20,30],
               [40,50,60],
               [70,80,90]])
print("Matrix:\n",mat)

Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [5]:
print("Second Column:\n",mat[:,1])
print()
print("FirstRow:\n",mat[0,:])

Second Column:
 [20 50 80]

FirstRow:
 [10 20 30]


In [6]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])
print("arr1 + arr2 =", arr1 + arr2)
print("arr1 * arr2 =", arr1 * arr2)
print("arr1 * 5 =", arr1 * 5)
print("arr2 - arr1 =", arr2 - arr1)

arr1 + arr2 = [11 22 33 44]
arr1 * arr2 = [ 10  40  90 160]
arr1 * 5 = [ 5 10 15 20]
arr2 - arr1 = [ 9 18 27 36]
